New tests
ONSdigital/es-disclosure-sg pull request #31
Opened 2020-03-20 14:15 UTC by Piwington

2020-03-20 14:58 UTC, KrisRogos submitted a review, later dismissed

2020-03-23 10:19 UTC, kingmushroom commented on tests/test_disclosure.py
> +
This section might need a comment to explain whats going on

2020-03-23 10:20 UTC, kingmushroom requested changes
Excellent stuff. Only point is that the one test looks a bit confusing, could we get a bit of explanation on it.

2020-03-23 10:37 UTC, kingmushroom approved these changes

2020-03-23 10:41 UTC, KrisRogos approved these changes

2020-03-23 10:42 UTC, merged